os: 
    - osx

language: c

compiler:
    - clang

before_install:
    - brew install https://raw.github.com/Homebrew/homebrew-core/master/Formula/llvm.rb
    - brew link llvm --overwrite
    - export PATH="/usr/local/opt/llvm/bin:$PATH"

script:
    - make
    - make tests
