os: 
    - osx

language: c

compiler:
    - clang

before_install:
    - brew install /homebrew/core/llvm
    - brew link llvm --overwrite
    - export PATH="/usr/local/opt/llvm/bin:$PATH"

script:
    - make
    - make tests
